#!/bin/bash

if [ $# -lt 1 ]; then
    printf "You must provide one argument:\n\tFirst: video ID\n\tSecond: Output file\n"
    exit 1
fi

if [ -z "${VIDEO_DOWNLOAD_PREFIX}" ]; then
    echo "VIDEO_DOWNLOAD_PREFIX is empty, cannot download video file!"
    exit 1
fi

fileID=$1
out=$2

url="${VIDEO_DOWNLOAD_PREFIX}${fileID}"

curl -o "${out}" "${url}"
