#!/bin/bash

if [ -z "${REDIS_USERNAME}" ]; then
    echo "REDIS_USERNAME not defined"
    exit 1
fi

if [ -z "${REDIS_PASSWORD}" ]; then
    echo "REDIS_PASSWORD not defined"
    exit 1
fi

if [ -z "${REDIS_HOST}" ]; then
    echo "REDIS_HOST not defined"
    exit 1
fi

if [ -z "${REDIS_PORT}" ]; then
    echo "REDIS_PORT not defined"
    exit 1
fi

if [ -z "${REDIS_JOB_QUEUE}" ]; then
    echo "REDIS_JOB_QUEUE not defined"
    exit 1
fi

if ! job="$(redis-cli --no-auth-warning -u "redis://${REDIS_USERNAME}:${REDIS_PASSWORD}@${REDIS_HOST}:${REDIS_PORT}" BLPOP "${REDIS_JOB_QUEUE}" 0 )"; then
    exit 1;
else
    echo "${job}" | tail -n +2
fi
