FROM golang AS build

WORKDIR /build
COPY go.mod /build/go.mod
COPY go.sum /build/go.sum

RUN go mod download

COPY contentdb /build/contentdb
COPY contentmanager /build/contentmanager

RUN go build -o content-manager ./contentmanager

FROM ubuntu AS ship

WORKDIR /app
COPY --from=build /build/content-manager /app
