FROM golang:1.19 AS build

WORKDIR /build
COPY go.mod /build/go.mod
COPY go.sum /build/go.sum

RUN go mod download

COPY roomdb /build/roomdb
COPY roomservice /build/roomservice

RUN go build -o room-service ./roomservice

FROM ubuntu:22.04 AS ship

WORKDIR /app
COPY --from=build /build/room-service /app
COPY docker-entrypoint.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh

RUN mkdir -p /data

ENTRYPOINT [ "/app/entrypoint.sh" ]