FROM golang:1.19 AS build

WORKDIR /build
COPY go.mod /build/go.mod
COPY go.sum /build/go.sum

RUN go mod download

COPY accountdb /build/accountdb
COPY accountservice /build/accountservice

RUN go build -o account-service ./accountservice

FROM ubuntu:22.04 AS ship

WORKDIR /app
COPY --from=build /build/account-service /app

RUN mkdir -p /data

ENTRYPOINT [ "/app/account-service", "-db", "/data/account.db" ]