package main

const veryLongText = `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus vitae consequat quam. Mauris commodo ipsum sit amet ex auctor pulvinar. Aenean quis nunc accumsan, suscipit sem et, feugiat nibh. Nulla convallis risus ut ipsum rutrum, quis sagittis massa suscipit. Duis lacus ex, mollis semper eros et, tempor interdum tellus. Quisque sed dignissim tellus, sed dapibus ex. Fusce lectus justo, facilisis congue aliquam aliquet, placerat quis lacus. Pellentesque sed scelerisque orci. Donec vehicula dolor non risus pharetra venenatis. Donec sollicitudin ornare purus, id tincidunt leo iaculis non. Sed tortor nulla, consectetur a eleifend in, faucibus sed sem. Vivamus vestibulum purus id magna consequat, eu egestas nibh condimentum. Sed condimentum, lorem eu faucibus feugiat, nunc lorem sagittis erat, quis mattis tortor massa in leo. Phasellus cursus, elit pulvinar blandit volutpat, risus purus convallis nunc, vel vestibulum ex nibh ut erat.
Phasellus tempor, lacus in consequat placerat, nisl mauris volutpat nisl, eget ultrices leo eros eu ex. Etiam aliquam lorem massa, id venenatis nisl placerat et. Maecenas in leo at ante tempor tempus. Donec mollis felis vel vestibulum pulvinar. Morbi et nulla in elit congue tincidunt. Sed scelerisque iaculis felis vitae eleifend. Phasellus condimentum est vel massa ultrices consequat.
Aenean sed ultrices erat, sed sagittis mi. Sed augue mauris, vehicula at ex sagittis, posuere aliquet sapien. Nullam congue pretium turpis at convallis. Duis dignissim ligula id facilisis hendrerit. Duis pulvinar ante eget justo dictum tincidunt. Duis leo arcu, porttitor quis volutpat in, ultrices ut tellus. Phasellus vehicula magna a ante egestas bibendum. Donec vestibulum ipsum nec massa feugiat maximus. Donec ultrices vitae dui a hendrerit. Mauris mattis ante a pretium accumsan. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Morbi aliquam nisi est, eget tincidunt sem rhoncus quis. Phasellus efficitur justo at ultrices fringilla. Sed nisl diam, elementum non magna in, consequat hendrerit erat. Aliquam in imperdiet lorem.
Sed ultricies nisi sit amet porttitor mattis. Morbi magna velit, accumsan vel enim quis, accumsan posuere lectus. Maecenas mattis feugiat enim a ullamcorper. Donec maximus quis lacus non hendrerit. Cras ut sagittis eros, sed placerat massa. Proin euismod est at leo viverra placerat. Quisque quis tincidunt est. Vestibulum condimentum augue ligula, id lacinia nulla iaculis vel. Interdum et malesuada fames ac ante ipsum primis in faucibus. Proin vel massa vel mauris pretium interdum.
Curabitur semper, nibh id aliquam molestie, risus nulla posuere dolor, non auctor felis elit eget leo. Nulla pretium ipsum a justo interdum, ornare gravida tellus feugiat. Ut non cursus lacus. Quisque posuere, risus sit amet porta tincidunt, turpis sapien malesuada quam, at dignissim est nisl vitae leo. Nullam tristique massa sed nibh sagittis, sed bibendum ex iaculis. Maecenas arcu dolor, rutrum a molestie nec, varius vitae felis. Curabitur sed enim felis.
Vivamus at tortor non mi fermentum facilisis et quis augue. Nullam imperdiet hendrerit libero, nec sodales urna hendrerit eu. Aliquam accumsan libero in sapien luctus, tristique imperdiet leo suscipit. Proin nec eleifend nulla. Phasellus ac euismod felis, eget accumsan erat. Suspendisse potenti. Nullam viverra pharetra odio, eget feugiat diam vestibulum eget. In vehicula congue molestie.
Donec sed faucibus felis, in convallis arcu. Nam mollis sit amet eros sit amet blandit. Curabitur vulputate neque non lorem consectetur ultricies. Integer a nulla nec neque congue volutpat. Curabitur scelerisque varius ante, et accumsan mauris aliquet sed. Fusce at faucibus ligula. Cras nec auctor dui, sit amet luctus leo. Suspendisse in scelerisque diam. Vestibulum at lectus massa. Fusce vel sollicitudin erat. Vestibulum vel lorem congue, venenatis ipsum eget, ullamcorper dolor.
Vestibulum justo urna, efficitur ut euismod in, vestibulum vitae tellus. Quisque ac suscipit mauris. Donec sed pulvinar ligula, vel ullamcorper tellus. Mauris ut libero aliquam, viverra urna nec, mattis lacus. Maecenas tempor, magna nec volutpat tincidunt, est elit iaculis diam, sit amet gravida nisl nibh eu nibh. Aenean consequat porttitor urna, et laoreet sapien. Maecenas luctus imperdiet felis. In quis justo metus. Maecenas sed eros tristique, porta tellus et, tempus sem. Donec malesuada velit nisl.
Donec molestie est nec nulla mollis blandit. Ut tempor tincidunt eros quis pretium. Curabitur dignissim eget mi vitae finibus. Fusce fermentum quam vitae tempus finibus. Vivamus ac tortor eget urna eleifend fringilla. Aenean maximus ante augue, at ultrices tortor fermentum at. Maecenas sed fringilla nisi. Nulla semper eros eu neque sodales, quis ornare nibh tincidunt. Mauris sed lorem nisl. Etiam risus ipsum, suscipit a consectetur eu, auctor sit amet tortor. Morbi fermentum auctor ultricies. Nulla cursus accumsan gravida.
Pellentesque pellentesque nibh eu auctor dictum. Nullam sed venenatis felis. Aliquam nec pharetra nunc. Sed vel diam at est varius suscipit. Donec sodales elit nec nisi hendrerit, quis fringilla nunc posuere. Maecenas ornare ligula eu turpis gravida sagittis. Curabitur nisl justo, lacinia eu semper id, condimentum nec ex. Maecenas ullamcorper malesuada est vestibulum tincidunt. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur non tellus ultricies, consectetur dui ac, consectetur magna. Nam blandit mauris sodales interdum tristique. Sed eget consequat metus, in vulputate massa. Cras metus diam, eleifend iaculis rhoncus non, sagittis rhoncus nunc.
Cras sed quam a dolor lacinia sollicitudin vitae et metus. Etiam vel efficitur risus, vel porta ante. Ut libero odio, finibus vel quam ut, elementum volutpat est. Donec dictum a dui ut mollis. In eu pretium erat. Integer convallis libero metus, eu sagittis dui condimentum sit amet. Vestibulum sagittis erat eget felis porta, a venenatis libero congue. Nunc in est in lectus mollis consectetur id vitae magna. Proin sit amet justo felis. Integer efficitur auctor diam in vehicula. Vestibulum finibus vitae massa quis ornare.
Donec gravida diam aliquet, mattis arcu eu, tempus dolor. Quisque nec pretium nisi. Fusce mauris quam, commodo ac lacus quis, scelerisque laoreet turpis. Sed eu lectus auctor, luctus ante quis, gravida felis. Nullam consectetur elit eu metus convallis, sed mattis quam feugiat. Quisque semper tempus quam. Interdum et malesuada fames ac ante ipsum primis in faucibus. Proin volutpat, erat et interdum pellentesque, magna elit dictum nisl, nec interdum elit nulla id enim. Mauris ante orci, lobortis at lectus at, aliquet luctus eros. Suspendisse cursus nisl eu est vestibulum varius. Etiam imperdiet leo ligula, vitae aliquet lectus euismod ut. Nulla velit erat, bibendum sed nisl id, euismod porttitor ante. Phasellus eu efficitur quam, eget vestibulum felis. Nullam et ipsum vehicula, laoreet augue eu, blandit massa. Morbi vulputate, orci vel eleifend luctus, sapien turpis ullamcorper odio, id tempus turpis ex pulvinar ante. Mauris placerat varius erat.
Integer at tortor et erat rhoncus imperdiet. Nulla feugiat, enim vel commodo posuere, mi neque dapibus nulla, a condimentum mi ligula porta leo. Mauris felis nunc, venenatis tempus nisi in, convallis dictum augue. Integer fermentum maximus ligula, nec commodo est egestas vitae. Fusce non rhoncus mauris. Sed auctor erat sit amet lacus mollis semper. Nullam in ante tortor. Fusce pharetra nec elit vitae tempus. Curabitur ante velit, vestibulum vitae sem euismod, malesuada commodo eros.
Praesent accumsan, sapien id vulputate auctor, lorem lorem viverra augue, elementum tempus metus urna sit amet lacus. In sed venenatis mauris, mattis eleifend erat. Vivamus consequat suscipit dui quis consectetur. Vivamus efficitur nibh quis consectetur volutpat. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus consequat quam vitae sem iaculis cursus. Nam lacus erat, placerat vitae lacinia nec, sagittis at erat. Duis maximus maximus condimentum. Curabitur eget turpis velit. Aenean varius blandit sapien, luctus interdum dui dapibus biam.`
